server:
  port: 8081
spring:
  application:
    #应用的名称，可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 15737979065@Zhl
  # redis
  redis:
    host: 192.168.72.100
    port: 6379
    password: "@Zhl157379"
    database: 0
  cache:
    redis:
      time-to-live: 3600000 #设置缓存数据的过期时间为一小时
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 1
#        time-between-eviction-runs: 10s
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
  # sqlMapper映射文件的放置位置
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.mysite.reggie.entity

# 将图片上传的路径放在d 盘下,在这里我将文件放在了当前的项目路径下
#reggie:
#  path: D:/
aliyun:
  oss:
    endPoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tSJpWq4ffGQaedrSSHm
    accessKeySecret: bBSKZCGEAlbbooXjTLy7NtGmjS9Oup
    bucketName: reggie-takeout-zhl
  sms:
    regionId: cn-hangzhou
    accessKeyId: LTAI5tJMcSCjs6XUxxJeBjQa
    accessKeySecret: LCy48PsnRD06FQnwsam7zHg5puE79f
    signName: 当当外卖
    templateCode: SMS_464081526